services:
  postgres:
    image: postgres:16-alpine
    container_name: cloudforge-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: cloudforge
      POSTGRES_USER: cloudforge
      POSTGRES_PASSWORD: cloudforge_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cloudforge -d cloudforge"]
      interval: 5s
      timeout: 5s
      retries: 10

  project-service:
    build:
      context: ./services/project-service
      dockerfile: Dockerfile
    image: cloudforge-project-service:local
    container_name: cloudforge-project-service
    restart: unless-stopped
    environment:
      APP_ENV: production
      SERVER_PORT: "8080"
      DATABASE_URL: postgres://cloudforge:cloudforge_password@postgres:5432/cloudforge?sslmode=disable
      SHUTDOWN_TIMEOUT_SECONDS: "10"
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget -q -O /dev/null http://127.0.0.1:8080/health || exit 1"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  infrastructure-service:
    build:
      context: ./services/infrastructure-service
      dockerfile: Dockerfile
    image: cloudforge-infrastructure-service:local
    container_name: cloudforge-infrastructure-service
    restart: unless-stopped
    environment:
      APP_ENV: production
      SERVER_PORT: "8081"
      DATABASE_URL: postgres://cloudforge:cloudforge_password@postgres:5432/cloudforge?sslmode=disable
      SHUTDOWN_TIMEOUT_SECONDS: "10"
    ports:
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget -q -O /dev/null http://127.0.0.1:8081/health || exit 1"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s


  deployment-service:
    build:
      context: ./services/deployment-service
      dockerfile: Dockerfile
    image: cloudforge-deployment-service:local
    container_name: cloudforge-deployment-service
    restart: unless-stopped
    environment:
      APP_ENV: production
      SERVER_PORT: "8082"
      DATABASE_URL: postgres://cloudforge:cloudforge_password@postgres:5432/cloudforge?sslmode=disable
      SHUTDOWN_TIMEOUT_SECONDS: "10"
    ports:
      - "8082:8082"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget -q -O /dev/null http://127.0.0.1:8082/health || exit 1"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s


  prometheus:
    image: prom/prometheus:v3.5.0
    container_name: cloudforge-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./monitoring/prometheus/rules:/etc/prometheus/rules:ro
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=7d"
      - "--web.enable-lifecycle"
    depends_on:
      deployment-service:
        condition: service_healthy

  grafana:
    image: grafana/grafana:12.1.1
    container_name: cloudforge-grafana
    restart: unless-stopped
    ports:
      - "3000:3000"

    environment:
      GF_SMTP_ENABLED: "true"
      GF_SMTP_HOST: "smtp.gmail.com:587"
      GF_SMTP_USER: "sufiyanmohammed098@gmail.com"
      GF_SMTP_PASSWORD: "kvycgmauzlehovyh"
      GF_SMTP_FROM_ADDRESS: "sufiyanmohammed098@gmail.com"
      GF_SMTP_FROM_NAME: "CloudForge AI Grafana"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

  alertmanager:
    image: prom/alertmanager:v0.28.1
    container_name: cloudforge-alertmanager
    restart: unless-stopped
    ports:
      - "9093:9093"
    volumes:
      - ./monitoring/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
      - alertmanager_data:/alertmanager
    command:
      - "--config.file=/etc/alertmanager/alertmanager.yml"
      - "--storage.path=/alertmanager"
    depends_on:
      - prometheus
volumes:
  postgres_data:
  prometheus_data:
  grafana_data:
  alertmanager_data:
